export const DIFFICULTIES: string[] = ['Easy', 'Medium', 'Hard', 'Expert'];

export const ROLES_CATEGORIZED: Record<string, string[]> = {
  'Software & Tech Roles': [
    'Software Engineer',
    'Full Stack Developer',
    'Frontend Developer (React, Angular, Vue)',
    'Backend Developer (Node.js, Django, Spring Boot)',
    'Python Developer',
    'Java Developer',
    'DevOps Engineer',
    'Machine Learning Engineer',
    'Data Scientist',
    'Data Analyst',
    'AI Research Engineer',
    'Cloud Engineer (AWS / Azure / GCP)',
    'Cybersecurity Analyst',
    'Mobile App Developer (Flutter / React Native)',
    'QA Engineer / Test Automation Engineer',
    'UI/UX Designer',
    'Game Developer',
    'Embedded Systems Engineer',
  ],
  'Management & Product Roles': [
    'Product Manager',
    'Project Manager',
    'Business Analyst',
    'Scrum Master',
    'Technical Program Manager',
    'Product Designer',
  ],
  'Business & Operations Roles': [
    'Marketing Manager',
    'Digital Marketing Executive',
    'Operations Manager',
    'HR Manager',
    'Talent Acquisition Specialist',
    'Sales Executive',
    'Customer Success Manager',
  ],
  'Finance & Data Roles': [
    'Financial Analyst',
    'Investment Analyst',
    'Accountant',
    'Risk & Compliance Officer',
    'Data Engineer',
  ],
  'Student & Entry-Level Roles': [
    'Intern (General / Tech / Marketing / HR / Finance)',
    'Graduate Trainee Engineer',
    'Junior Developer',
    'Research Assistant',
  ],
  'Specialized AI & Data Roles': [
    'NLP Engineer',
    'Computer Vision Engineer',
    'Generative AI Engineer',
    'Prompt Engineer',
    'AI Ethics & Policy Analyst',
  ],
};